destination: VS Code debug specs - Ruby on Rails
title: VS Code debug specs - Ruby on Rails
theme: jekyll-theme-cayman
gems:
  - jekyll-readme-index
readme_index:
  enabled: true
  remove_originals: false
